---
- hosts: nginx
  tasks:
    - name: ensure nginx is at the latest version
      yum: name=nginx state=latest
      become: yes
    - name: start nginx
      service:
          name: nginx
          state: started
      become: yes
    - name: copy the nginx config file and restart nginx
      copy:
        src: ~/ansible/upstreams.conf
        dest: /etc/nginx/conf.d/upstreams.conf
      become: yes
    - name: copy the nginx config file and restart nginx
      copy:
        src: ~/ansible/nginx.conf
        dest: /etc/nginx/nginx.conf
      become: yes
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes
